<!DOCTYPE html>
<html lang="en">
<title>Catalog</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<link rel="stylesheet" href="/public/assets/css/style.css">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="/public/assets/js/products.js"></script>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Home</a>
    <a class="navbar-brand" href="/admin">Admin panel</a>
</nav>

<div class="container">
    <div class="content_page">
        <?php
        $numberOfColumns = 3;
        $bootstrapColWidth = 12 / $numberOfColumns;

        $arrayChunks = array_chunk($products, $numberOfColumns);
        foreach ($arrayChunks as $products) {
            echo '<div class="row">';
            foreach ($products as $item) {
                echo '<div class="col-md-' . $bootstrapColWidth . '">'; ?>
                <div class="col-md-12">
                    <?php echo $item['title'] ?>
                </div>
                <div class="col-md-12">
                    <?php echo '<img src="' . $item['image_path'] . $item['image_name'] . '">'; ?>
                </div>
                <div class="col-md-12">
                    <?php echo $item['description'] ?>
                </div>
                <?php echo '</div>';
            }
            echo '</div>';
        }
        ?>
    </div>

    <h2>Comments</h2>
    <div class="comments_div">
        <?php foreach ($comments as $comment): ?>
            <table class="table table-striped" id="comments_table">
                <tr>
                    <th>title</th>
                    <td><?php echo $comment['title'] ?></td>
                </tr>
                <tr>
                    <th>email</th>
                    <td><?php echo $comment['email'] ?></td>
                </tr>
                <tr>
                    <th>text</th>
                    <td><?php echo $comment['text'] ?></td>
                </tr>
            </table>
            <hr>
            <br>
        <?php endforeach; ?>
    </div>

    <div id="add_comment_div" class="col-md-4">
        <h2>Add new comment</h2>
        <form id="add_comment_form" method="post" action="/save-comment">
            <div class="form-group">
                <label class="sr-only" for="title">title</label>
                <input type="text" name="title" id="title" class="form-control" placeholder="title">
            </div>
            <div class="form-group">
                <label class="sr-only" for="email">email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="email">
            </div>
            <div class="form-group">
                <label class="sr-only" for="text">text</label>
                <textarea name="text" id="text" class="form-control" rows="3"></textarea>
            </div>
            <button type="button" class="btn btn-primary" onclick="saveComment()">save</button>
        </form>
    </div>
</div>